site_name: OpendTect Plugins
repo_url: https://github.com/waynegm/OpendTect-Plugins
site_description: Documentation for WAYNEGM's OpendTect plugins
site_author: Wayne Mogg
site_favicon: favicon-32x32.png
copyright: All content and images &copy; 2015 by Wayne Mogg
google_analytics: ['UA-62607269-1', 'OpendTect-Plugin-Docs']
theme: flatly
pages:
- Home: 'index.md'
- Installation:
    - Download: 'Installation/download-binary.md'
    - Install: 'Installation/installation.md'
    - Build from source: 'Installation/building-from-source.md'
    - Issues/FAQ: 'Installation/faq.md'
- Plugins:
    - AVO attributes: 'Attributes/AVOAttrib.md'
    - External attributes: 'Attributes/ExternalAttrib.md'
    - Gradient attribute: 'Attributes/GradientAttrib.md'
    - Local time-frequency attribute: 'Attributes/LTFAttrib.md'
    - Mean of least variance filter: 'Attributes/MLVFilter.md'
    - Recursive time-frequency decomposition: 'Attributes/RSpecAttrib.md'
- External Attributes:
    - Introduction: 'External_Attributes/ExternalAttributes.md'
    - AVO Intercept and Gradient: 'External_Attributes/AVO_IG.md'
    - Dip and Azimuth: 'External_Attributes/DipandAzimuth.md'
    - LPA Smoothing: 'External_Attributes/LPA_Smooth.md'
    - Local polynomial approximation: 'External_Attributes/LPA_Attributes.md'
    - Spatial filter - Circular: 'External_Attributes/Spatial_Filter_Circular.md'
    - Spatial filter - Rectangular: 'External_Attributes/Spatial_Filter_Rectangular.md'
    - Vector Filters: 'External_Attributes/Vector_Filters.md'
    - Z Delay Estimation: 'External_Attributes/Z_Delay_Est.md'
    - Zero crossing trace block: 'External_Attributes/ZC_Block.md'
- About:
    - License: 'license.md'
    - Release notes: 'relnotes.md'

markdown_extensions: 
    - pymdownx.arithmatex
    
extra_css:
    - css/juxtapose.css
    
extra_javascript:
    - js/juxtapose.min.js
    - js/mathjax-config.js
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
    

